name: ssh command
on: push
jobs:
  ssh-setup:
    runs-on: ubuntu-latest
    steps:
     - run: |
            cd /home
            sudo mkdir -p .ssh && chmod 700 .ssh
            cd /home/.ssh
            ls
            ssh-keyscan -H ${{ secrets.SSH_HOST }} >> .ssh/known_hosts
            ls
            touch .ssh/id #&& chmod 600 .ssh/id
            echo "${{secrets.SSH_PUB_KEY}}" > .ssh/id
            chmod 600 .ssh/id
            ssh -F /dev/null -tt -i .ssh/id root@${{ secrets.SSH_HOST }}
     #- run: touch ~/.ssh/id_rsa.pub && chmod 600 ~/.ssh/id_rsa.pub
     #- run: echo "${{secrets.SSH_PUB_KEY}}" > ~/.ssh/id_rsa.pub
     #- run: chmod 600 ~/.ssh/id_rsa.pub
     #- run: cat  ~/.ssh/id_rsa
     #- run: eval `ssh-agent -s`
     #- run: sudo ssh-add ~/.ssh/id_rsa
     #- run: sudo ssh-add -l
     #- run: sudo echo $SSH_AGENT_SOCK
