name: ssh command
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
     - run: mkdir -p ~/.ssh && chmod 700 ~/.ssh
     - run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
     - run: ssh root@${{ secrets.SSH_HOST }}