name: ssh command
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
     - run: mkdir -p ~/.ssh && chmod 700 ~/.ssh
     - run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
     - run: touch ~/.ssh/id_rsa && chmod 700 ~/.ssh/id_rsa
     - run: ls  ~/.ssh
     - run: echo "${{secrets.SSH_PRIVATE_KEY}}" >> ~/.ssh/id_rsa
     - run: touch ~/.ssh/id_rsa.pub && chmod 700 ~/.ssh/id_rsa.pub
     - run: echo "${{secrets.SSH_PUB_KEY}}" >> ~/.ssh/id_rsa.pub
     - run: echo $SSH_AGENT_SOCK
     - run: ssh root@${{ secrets.SSH_HOST }}