name: ssh command
on: push
jobs:
  ssh-setup:
    runs-on: ubuntu-latest
    steps:
     - run: |
            mkdir -p ~/.ssh
            touch ~/.ssh/known_hosts
            ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
            touch ~/.ssh/id
            echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id
            chmod 600 ~/.ssh/known_hosts
            chmod 600 ~/.ssh/id
            chmod 700 ~/.ssh
            eval `ssh-agent -s`
            ssh-add ~/.ssh/id
            ssh-add -l
            ssh  -tt -i ~/.ssh/id root@${{ secrets.SSH_HOST }}

     #-F /dev/nullsudo 
     #- run: touch ~/.ssh/id_rsa.pub && chmod 600 ~/.ssh/id_rsa.pub
     #- run: echo "${{secrets.SSH_PUB_KEY}}" > ~/.ssh/id_rsa.pub
     #- run: chmod 600 ~/.ssh/id_rsa.pub
     #- run: cat  ~/.ssh/id_rsa
     #- run: 
     #- run: sudo _rsa
     #- run: 
     #- run: sudo echo $SSH_AGENT_SOCK
