name: ssh command
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
     - run: mkdir -p ~/.ssh && chmod 700 ~/.ssh
     - run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
     - run: touch ~/.ssh/id_rsa
     - run: echo ${{secrets.SSH_PRIVATE_KEY}} > ~/.ssh/id_rsa
     - run: touch ~/.ssh/id_rsa.pub
     - run: echo ${{secrets.SSH_PUB_KEY}} > ~/.ssh/id_rsa.pub
     - run: ssh root@${{ secrets.SSH_HOST }}