name: ssh command
on: push
jobs:
  ssh-setup:
    runs-on: ubuntu-latest
    steps:
     - run: |
            cd /home/
            sudo mkdir -p /home/.ssh # && chmod 700 /home/.ssh
            sudo touch /home/.ssh/known_hosts #&& chmod 600 /home/.ssh/known_hosts
            sudo ssh-keyscan -H ${{ secrets.SSH_HOST }} >> /home/.ssh/known_hosts
            ls
            sudo touch /home/.ssh/id #&& chmod 600 /home/.ssh/id
            sudo echo "${{secrets.SSH_PUB_KEY}}" > /home/.ssh/id
            sudo chmod 600 /home/.ssh/id
            sudo ssh -F /dev/null -tt -i /home/.ssh/id root@${{ secrets.SSH_HOST }}
     #- run: touch ~/.ssh/id_rsa.pub && chmod 600 ~/.ssh/id_rsa.pub
     #- run: echo "${{secrets.SSH_PUB_KEY}}" > ~/.ssh/id_rsa.pub
     #- run: chmod 600 ~/.ssh/id_rsa.pub
     #- run: cat  ~/.ssh/id_rsa
     #- run: eval `ssh-agent -s`
     #- run: sudo ssh-add ~/.ssh/id_rsa
     #- run: sudo ssh-add -l
     #- run: sudo echo $SSH_AGENT_SOCK
