name: ssh command
on: push
jobs:
  ssh-setup:
    runs-on: ubuntu-latest
    steps:
     - run: |
            cd /home/
            cd ..
            mkdir -p /home/.ssh
            touch /home/.ssh/known_hosts #&& chmod 600 /home/.ssh/known_hosts
            ssh-keyscan -H ${{ secrets.SSH_HOST }} >> /home/.ssh/known_hosts
            touch /home/.ssh/id
            echo "${{secrets.SSH_PUB_KEY}}" > /home/.ssh/id
            chmod 600 /home/.ssh/id && chmod 700 /home/.ssh
            ssh -F /dev/null -tt -i /home/.ssh/id root@${{ secrets.SSH_HOST }}


     #- run: touch ~/.ssh/id_rsa.pub && chmod 600 ~/.ssh/id_rsa.pub
     #- run: echo "${{secrets.SSH_PUB_KEY}}" > ~/.ssh/id_rsa.pub
     #- run: chmod 600 ~/.ssh/id_rsa.pub
     #- run: cat  ~/.ssh/id_rsa
     #- run: eval `ssh-agent -s`
     #- run: sudo ssh-add ~/.ssh/id_rsa
     #- run: sudo ssh-add -l
     #- run: sudo echo $SSH_AGENT_SOCK
