name: ssh command
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
     - run: mkdir -p ~/.ssh && chmod 700 ~/.ssh
     - run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
     - run: touch ~/.ssh/id_rsa
     - run: ls  ~/.ssh
     - run: echo "${{secrets.SSH_PRIVATE_KEY}}" >> ~/.ssh/id_rsa
     - run: touch ~/.ssh/id_rsa.pub
     - run: echo "${{secrets.SSH_PUB_KEY}}" >> ~/.ssh/id_rsa.pub
     #- run: cat  ~/.ssh/id_rsa
     #- run: eval `ssh-agent -s`
     #- run: sudo ssh-add ~/.ssh/id_rsa
     #- run: sudo ssh-add -l
     #- run: sudo echo $SSH_AGENT_SOCK
     - run: sudo ssh root@${{ secrets.SSH_HOST }}\
