name: ssh command
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
     - run: sudo apt-get install openssh-server -t ~/
     - run: sudo systemctl enable ssh
     - run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      