name: deploy-on-droplet
on: push
jobs:
  deploy-on-droplet:
    runs-on: ubuntu-latest
    steps:
     - name: ssh-setup
     - run: |
            mkdir -p ~/.ssh
            touch ~/.ssh/known_hosts
            ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
            touch ~/.ssh/id
            echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id
            chmod 600 ~/.ssh/known_hosts
            chmod 600 ~/.ssh/id
            chmod 700 ~/.ssh 
            ssh  -tt -i ~/.ssh/id root@${{ secrets.SSH_HOST }}