name: deploy_on_droplet
on: push
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
     - name: setting-ssh-key
       run: |
             ssh-add ${{secrets.SSH_PRIVATE_KEY}}
             ssh-keyscan ${{secrets.SSH_HOST}}

